baseURL = 'https://mamadadapapamama.github.io/blogblog/'
languageCode = 'en'
title = 'Just Vibing & Trying'
theme = 'PaperMod'

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true